name: "Aras-GP-docker"

services:
  Aras-GP:
    image: .
    container_name: "Aras-GP"
    restart: unless-stopped
    networks:
      - Aras-GP-proxy
    ports:
      - "8085:8085" # http port
      - "1080:1080" # socks5 port

networks:
  Aras-GP-proxy:
    name: Aras-GP-proxy
    driver: bridge
    external: false
